### PR TITLE
first commit; updated README.md to 0.3.2

### PR DESCRIPTION
**Pull request by pdenno**
I only changed the version number that is used in the Leinengen dependencies; it said 0.3.0; I suppose it should be 0.3.2.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
Thanks for fixing that oversight!

**Comment by pdenno** [comment]
On 2015-07-23 8:57 AM, James A. Overton wrote:

> Thanks for fixing that oversight!
> 
> No problem. I only have 1 day's experience with owlapi, but it looks 
> very nice. I was wondering, is there something in there to express 
> property characteristics (e.g. owl:FunctionalProperty, 
> http://www.w3.org/TR/2012/REC-owl2-primer-20121211/#Domain_and_Range_Restrictions)? 
> Would it be hard to add? (I'd do the work, if I can figure out the java 
> owl-api).

Best regards,
   Peter

**Comment by jamesaoverton** [comment]
No, those aren't wrapped. The focus has been on classes and annotations. But they shouldn't be much different than the other wrapper functions.

I'd be happy to accept those additions. If you decide to do that, please open a tracker item so we can discuss the design.

But before investing too much time in that, take a look at these projects to see if any of them suit your needs better:
- https://github.com/phillord/tawny-owl
- https://github.com/ontodev/edn-ld
- https://github.com/ontodev/robot

**Comment by jamesaoverton** [comment]
Yes, Tawny-OWL aims to be interactive, and combined with Emacs to work as an IDE for ontology development. That's not my use case. But the author has worked hard on documentation for users:
- http://homepages.cs.ncl.ac.uk/phillip.lord/take-wing/take_wing.html
- https://github.com/phillord/tawny-tutorial

**Comment by pdenno** [comment]
On 2015-07-23 10:28 AM, James A. Overton wrote:

> But the author has worked hard on documentation for users

Certainly. It is well documented for its use case. I did mean to be 
critical.

Best regards,
    Peter

**Comment by pdenno** [comment]
Hi James,

On 2015-07-23 9:32 AM, James A. Overton wrote:

> But before investing too much time in that, take a look at these 
> projects to see if any of them suit your needs better:
> - https://github.com/phillord/tawny-owl
> - https://github.com/ontodev/edn-ld
> 
> Your edn-ld looks interesting. I played around with it some and found it 
> easy to use. I got stuck trying to output blank nodes in turtle however. 
> I couldn't see any obvious problem in your code. In fact, Jena output 
> invalid ttl (omits the subject entirely when the subject is a blank 
> node). There is a problem here with Jena, at least. Any ideas?

Three blank nodes were used; the following resulted:

@prefix mfi:   http://modelmeth.nist.gov/mfi/ .
@prefix rdf:   http://www.w3.org/1999/02/22-rdf-syntax-ns# .
@prefix xsd:   http://www.w3.org/2001/XMLSchema# .

[ a                  mfi:MathRelation ;
   mfi:hasLHS         [ a               mfi:MathVariable ;
                        mfi:hasVarName  "Y"^^xsd:string
                      ] ;
   mfi:hasRHS         [ a               mfi:MathVariable ;
                        mfi:hasVarName  "X"^^xsd:string
                      ] ;
   mfi:hasRelationOp  mfi:MathRelationEquality
] .

Best regards,
    Peter

**Comment by jamesaoverton** [comment]
Looks like a bug, probably in my code. Can you please add an issue to the EDN-LD tracker, including the Clojure code you used, and I'll look at it as soon as I get a chance. (Maybe not very soon, but I'll try my best.) Thanks again!

**Pull request merged**
